In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print X

[[  4.77708299  -5.58872958  -9.38752618 ...,  -5.99546302 -11.28543996
   -2.93373952]
 [  3.81672241 -12.5665225   -4.60344982 ...,  -0.6462159    1.03920534
   -5.29892342]
 [ 13.1235719    7.27228301   3.04210846 ...,  -2.54070618   1.85391944
   -6.27323723]
 ..., 
 [ -5.44898229   0.25774713   8.63667427 ...,  -0.9109768   -7.88258476
    8.37337829]
 [ 10.07663213  13.00792948   8.63383605 ...,  15.51490837 -12.60983086
   15.05678614]
 [-13.65810886 -10.18376879  17.73032294 ...,  -2.27001897   7.9138699
  -10.0645259 ]]


In [3]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print X_norm

[[ 0.3678741  -0.68127748 -1.00191247 ..., -0.66114241 -1.24536631
  -0.39998994]
 [ 0.27179897 -1.36525752 -0.52290301 ..., -0.14550484  0.00621958
  -0.64446975]
 [ 1.2028626   0.5793899   0.24261461 ..., -0.32812313  0.08895499
  -0.74518076]
 ..., 
 [-0.65514851 -0.10819178  0.80277498 ..., -0.17102632 -0.89980135
   0.76878263]
 [ 0.89804465  1.14161175  0.8024908  ...,  1.41233732 -1.37986015
   1.45962038]
 [-1.47639518 -1.13169427  1.7132838  ..., -0.30203039  0.70435189
  -1.13707145]]


In [4]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
r = np.sum(Z, axis=1)


In [5]:
print np.nonzero(r <= 9)

(array([0, 2, 3]),)


In [6]:
A = np.eye(3)
print A

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
B = np.eye(3)
print B

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
AB = np.vstack((A, B))
print AB

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
